// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsnTsVPL06ZAWVW5ZFCqxj_4lox8JegU',
    appId: '1:723893184729:web:a497dabc2751af3ab6f6c8',
    messagingSenderId: '723893184729',
    projectId: 'gamebox-78679',
    authDomain: 'gamebox-78679.firebaseapp.com',
    storageBucket: 'gamebox-78679.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiD_7QsDlDFpWmNyCWUJghYCeG7ZmyXQ8',
    appId: '1:723893184729:android:2c4524cd09c63a5bb6f6c8',
    messagingSenderId: '723893184729',
    projectId: 'gamebox-78679',
    storageBucket: 'gamebox-78679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48nAaF3WT0Esa5fzOtsajmiD1A9nPXPA',
    appId: '1:723893184729:ios:d10b23a8a34bc738b6f6c8',
    messagingSenderId: '723893184729',
    projectId: 'gamebox-78679',
    storageBucket: 'gamebox-78679.firebasestorage.app',
    iosBundleId: 'com.example.gameBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC48nAaF3WT0Esa5fzOtsajmiD1A9nPXPA',
    appId: '1:723893184729:ios:d10b23a8a34bc738b6f6c8',
    messagingSenderId: '723893184729',
    projectId: 'gamebox-78679',
    storageBucket: 'gamebox-78679.firebasestorage.app',
    iosBundleId: 'com.example.gameBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcsnTsVPL06ZAWVW5ZFCqxj_4lox8JegU',
    appId: '1:723893184729:web:3de796d7f91c136bb6f6c8',
    messagingSenderId: '723893184729',
    projectId: 'gamebox-78679',
    authDomain: 'gamebox-78679.firebaseapp.com',
    storageBucket: 'gamebox-78679.firebasestorage.app',
  );
}
